### ISSUE TITLE
Pruebas adicionales

### ISSUE THREAD

**Issue by cmonsalvec** [jjjohncedeno/ExCedenoJohnSum#1]
Estimado John, 

Favor asegurarse que las siguientes pruebas funcionan:

Nota: podría ser que la versión de Junit no sea la que está usando, ni los nombres de las clases probadas sean las mismas, entonces primero adaptar las pruebas según su trabajo.

Si termina esto, entonces espero me permita ver por este medio los resultados de las pruebas (captura), y el código correspondiente a las pruebas.

@Test
public void cuandoUnSoloNumeroEsUsadoSeRetornaEseValor() {
Assert.assertEquals(3, Sumador("3"));
}
 
@Test
public void cuandoDosNumerosSonUsadosEntoncesRetornamosSuSuma() {
Assert.assertEquals(9, Sumador("3,6"));
}

**Comment by jjjohncedeno** [comment]
Buenos Dias, 

Comunico que las pruebas pedidas funcionan. Adjunto una captura con los resultados y el código correspondiente.

Saludos.

![pruebas adicionales 1](https://cloud.githubusercontent.com/assets/8129391/22699844/aca249b6-ed26-11e6-97ee-4dae9672c234.png)
