### ISSUE TITLE
Deseo sumar más de dos números

### ISSUE THREAD

**Issue by cmonsalvec** [jjjohncedeno/ExCedenoJohnSum#2]
Estimado John,

Deseo que Sumadora pueda sumar más de dos números. Por ejemplo, debería poderse generar una prueba basado en el siguiente Assert:

Assert.assertEquals(3+6+15+18+46+33, Sumadora("3,6,15,18,46,33"));

Nuevamente, puede ser que se deba adaptar el Assert para el proyecto. Igual que antes notificarme por este medio el resultado de la prueba exitosa, y realizar el commit respectivo.

Gracias

**Comment by jjjohncedeno** [comment]
Buenos Días,

Comunico que el arreglo pedido, con sus respectivas pruebas, fue realizado. Adjunto una captura con los resultados y el código correspondiente.

Saludos.

![sumar mas de dos numeros](https://cloud.githubusercontent.com/assets/8129391/22700303/30630186-ed28-11e6-92cd-ca428df68866.png)
